name: Build Test Image
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-test-image.yml"
      - "test/Dockerfile"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        keycloak-version:
          - '23.0.3'
          - '22.0.5'
          - '21.0.1'
          - '20.0.5'
          - '19.0.2'

      fail-fast: false
    concurrency:
      group: docker-build-${{ matrix.keycloak-version }}
      cancel-in-progress: true
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/qedsoftware/keycloak-dev:${{ matrix.keycloak-version }}
          file: test/Dockerfile
          build-args: |
            KEYCLOAK_VERSION=${{ matrix.keycloak-version }}
